# Generated by Django 5.0.6 on 2026-05-25 00:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='color hex')),
                ('icon', models.CharField(blank=True, default='calendar', max_length=50, verbose_name='icono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='descripción')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='descripción corta')),
                ('event_type', models.CharField(choices=[('presential', 'Presencial'), ('virtual', 'Virtual'), ('hybrid', 'Híbrido')], default='presential', max_length=20, verbose_name='tipo')),
                ('start_date', models.DateTimeField(verbose_name='fecha inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha fin')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='ubicación')),
                ('address', models.TextField(blank=True, verbose_name='dirección')),
                ('virtual_link', models.URLField(blank=True, verbose_name='enlace virtual')),
                ('virtual_platform', models.CharField(blank=True, max_length=100, verbose_name='plataforma virtual')),
                ('max_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacidad máxima')),
                ('current_attendees', models.PositiveIntegerField(default=0, verbose_name='asistentes actuales')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='imagen de portada')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='draft', max_length=20, verbose_name='estado')),
                ('is_public', models.BooleanField(default=True, verbose_name='es público')),
                ('is_free', models.BooleanField(default=True, verbose_name='es gratuito')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio')),
                ('tags', models.CharField(blank=True, help_text='Separadas por coma', max_length=500, verbose_name='etiquetas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-start_date'],
            },
        ),
    ]
