services:
  - type: web
    name: izag-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    healthCheckPath: /api/schema/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: izag-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: izag-redis
          type: redis
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "Izag Gestión Eventos <noreply@izag-eventos.com>"
      - key: PYTHON_VERSION
        value: "3.12.0"

  - type: worker
    name: izag-celery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config worker -l INFO --concurrency 2"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        fromService:
          name: izag-web
          type: web
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: izag-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: izag-redis
          type: redis
          property: connectionString

  - type: worker
    name: izag-celery-beat
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        fromService:
          name: izag-web
          type: web
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: izag-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: izag-redis
          type: redis
          property: connectionString

databases:
  - name: izag-db
    databaseName: izag
    user: izag
    plan: free

  - name: izag-redis
    type: redis
    plan: free
    ipAllowList: []
