# Generated by Django 5.0.6 on 2026-05-25 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('waitlisted', 'Lista de espera'), ('checked_in', 'Registrado')], default='confirmed', max_length=20, verbose_name='estado')),
                ('checked_in', models.BooleanField(default=False, verbose_name='registrado en evento')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=12, unique=True, verbose_name='código de confirmación')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='código QR')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-registration_date'],
            },
        ),
    ]
