# Generated by Django 5.0.6 on 2026-05-25 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'status'], name='registratio_event_i_246b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user', 'status'], name='registratio_user_id_e3aac6_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['confirmation_code'], name='registratio_confirm_42f962_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'event')},
        ),
    ]
