# Generated by Django 5.0.6 on 2026-05-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('registration_confirmed', 'Registro Confirmado'), ('registration_cancelled', 'Registro Cancelado'), ('event_reminder', 'Recordatorio'), ('event_cancelled', 'Evento Cancelado'), ('waitlist_promoted', 'Ascendido de lista de espera')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
